export const USER_LOGIN = "USER_LOGIN";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER = "USER_REGISTER";
export const CREATE_BOOK = "CREATE_BOOK";
export const GET_BOOK_LIST = "GET_BOOK_LIST";
export const GET_BOOK_DETAIL = "GET_BOOK_DETAIL";
export const UPDATE_BOOK_DETAIL = "UPDATE_BOOK_DETAIL";
export const DELETE_BOOK = "DELETE_BOOK";

export const ADD_NOTIFY_MESSAGE = "ADD_NOTIFY_MESSAGE";
export const REMOVE_NOTIFY_MESSAGE = "REMOVE_NOTIFY_MESSAGE";
export const RESET_NOTIFY_MESSAGE = "RESET_NOTIFY_MESSAGE";

export const API_REQUEST_SEND = 'API_REQUEST_SEND';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';